# Generated by Django 3.2.18 on 2023-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('url', models.CharField(max_length=20, verbose_name='URL театра')),
                ('name', models.CharField(max_length=20, verbose_name='Название театра')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('information', models.TextField(verbose_name='Информация о театре')),
                ('image_source', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'theatres',
                'managed': False,
            },
        ),
    ]
