# Generated by Django 3.2.18 on 2023-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='Название района')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='Название постановки')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perfomances',
                'managed': False,
            },
        ),
    ]
